### ISSUE TITLE
Coconut roadmap

### ISSUE THREAD

**Issue by AbdelStark** [AbdelStark/coconut#2]
Mint Features:

- Supported backends
  - [ ] LNbits
  - [ ] Lnd
  - [ ] Alby
  - [ ] Strike
  - [ ] core-lightning (WIP)

Wallet Features:

- [ ] connect to mint (load keys)
- [ ] request minting tokens
- [ ] minting tokens
- [ ] sending tokens (get an encoded token for chosen value)
- [ ] receiving tokens
- [ ] melting tokens
- [ ] check if tokens are spent
- [ ] multi mint support

Implemented [NUTs](https://github.com/cashubtc/nuts/):

- [ ] [NUT-00](https://github.com/cashubtc/nuts/blob/main/00.md)
- [ ] [NUT-01](https://github.com/cashubtc/nuts/blob/main/01.md)
- [ ] [NUT-02](https://github.com/cashubtc/nuts/blob/main/02.md)
- [ ] [NUT-03](https://github.com/cashubtc/nuts/blob/main/03.md)
- [ ] [NUT-04](https://github.com/cashubtc/nuts/blob/main/04.md)
- [ ] [NUT-05](https://github.com/cashubtc/nuts/blob/main/05.md)
- [ ] [NUT-06](https://github.com/cashubtc/nuts/blob/main/06.md)
- [ ] [NUT-07](https://github.com/cashubtc/nuts/blob/main/07.md)
- [ ] [NUT-08](https://github.com/cashubtc/nuts/blob/main/08.md)
- [ ] [NUT-09](https://github.com/cashubtc/nuts/blob/main/09.md)
- [ ] [NUT-10](https://github.com/cashubtc/nuts/blob/main/10.md)
- [ ] [NUT-11](https://github.com/cashubtc/nuts/blob/main/11.md)
- [ ] [NUT-12](https://github.com/cashubtc/nuts/blob/main/12.md)
- [ ] [NUT-13](https://github.com/cashubtc/nuts/blob/main/13.md)
- [ ] [NUT-14](https://github.com/cashubtc/nuts/blob/main/14.md)
- [ ] [NUT-15](https://github.com/cashubtc/nuts/blob/main/15.md)
- [ ] [NUT-16](https://github.com/cashubtc/nuts/blob/main/16.md)
- [ ] NUT-17 on-chain mint (unofficial nut)
- [ ] NUT-18 on-chain melt (unofficial nut)
